[package]
name = "linux2rest"
version = "0.1.0"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
chrono = "0.4"
env_logger = "0.8"
lazy_static = "1.4"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
structopt = { version = "0.3", default-features = false }

#Features
netstat2 = "0.9"
pnet = "0.27.2"
rmesg = { version = "1.0.14", features = ["extra-traits"] }
rppal = "0.11.3"
udev = "0.6"
sysinfo = { git = "https://github.com/GuillaumeGomez/sysinfo", branch="master" }

[build-dependencies]
reqwest = {version = "0.11", features = ["blocking"]}
vergen = {version = "4", default-features = false, features = ["build", "git"]}
