[package]
name = "linux2rest"
version = "0.1.0"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
actix-web = "1.0.8"
clap = "2.31.2"
rscam = { git = "https://github.com/patrickelectric/rscam", branch = "master" }
serde_json = "1.0.41"
serde = { version = "1.0.104", features = ["derive"] }
